version: "3.8"

services:
  db:
    image: postgres:13.4
    env_file:
      - ./docker/env.db

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: "./manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./docker/env.db
    container_name: blango
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/code
    depends_on:
      - db
